- name: Update fullstack to a specific intermediate revision
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    disable_edx_services: true
    mongo_enable_journal: false
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    EDXAPP_MONGO_HOSTS: ['mongo']
    EDXAPP_MYSQL_HOST: 'staging-edx.cd8vpdwrz60w.us-east-1.rds.amazonaws.com'
    EDXAPP_MYSQL_CSMH_HOST: "{{ EDXAPP_MYSQL_HOST }}"
    XQUEUE_MYSQL_HOST: "{{ EDXAPP_MYSQL_HOST }}"
    ORA_MYSQL_HOST: "{{ EDXAPP_MYSQL_HOST }}"
  roles:
    - common
    - vhost
    - edxapp
    - xqueue
