- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    edx_platform_repo: "https://github.com/Livit/Livit.Learn.EdX.git"
    edx_ansible_source_repo: "https://github.com/Livit/Livit.Learn.EdX.configuration.git"
    migrate_db: 'yes'
    devstack: true
    disable_edx_services: true
    mongo_enable_journal: false
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    ECOMMERCE_DJANGO_SETTINGS_MODULE: "ecommerce.settings.devstack"
  roles:
    - common
    - vhost
    - edx_ansible
    - mysql
    - edxlocal
    - memcache
    - mongo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - edxapp
    - oraclejdk
    - elasticsearch
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
    - browsers
    - browsermob-proxy
    - local_dev
    - demo
    - oauth_client_setup
